application:
  name: handoutify
  project: handoutify
  publicly_accessible: true
  cpu: 1
routers:
- name: main
  custom_domains:
  - branch: master
    domain: handoutify.tools.nilsand.re
  routes:
  - application_name: handoutify
    paths:
    - /
